version: '3.7'

services:
  webfrontend:
    image: ${DOCKER_REGISTRY:-xuanhnvt}/webfrontend
    build:
      context: ./WebFrontEnd
      dockerfile: Dockerfile
    networks:
    - backend
    depends_on:
    - mywebapi

  mywebapi:
    image: ${DOCKER_REGISTRY:-xuanhnvt}/mywebapi
    build:
      context: ./MyWebApi
      dockerfile: Dockerfile
    networks:
      - backend
    depends_on:
    - identityserver
  
  identityserver:
    image: ${DOCKER_REGISTRY:-xuanhnvt}/identityserver
    build:
      context: ./IdentityServer
      dockerfile: Dockerfile
    networks:
      - backend
networks:
  backend:
