version: '3.4'

services:
  webfrontend:
    image: ${DOCKER_REGISTRY-}webfrontend
    build:
      context: ./WebFrontEnd
      dockerfile: Dockerfile
    environment: 
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://0.0.0.0:5000
    - MYWEBAPI_URL=http://mywebapi1
    ports:
    - "8080:5000"

  mywebapi1:
    image: ${DOCKER_REGISTRY-}mywebapi
    build:
      context: ./MyWebApi
      dockerfile: Dockerfile
