version: '3.7'

services:
  webfrontend:
    environment: 
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://0.0.0.0:80
    - MYWEBAPI_URL=http://mywebapi
    ports:
    - "5002:80"

  mywebapi:
    environment: 
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://*:80
    - IdentityUrl=http://identityserver:5000
    ports: 
    - 5001:80
  
  identityserver:
    environment: 
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://*:5000
    - IDENTITY_ISSUER=http://localhost:5000
    ports:
    - 5000:5000
