version: '3.4'

services:
  webfrontend:
    image: ${DOCKER_REGISTRY-}webfrontend
    build:
      context: ./WebFrontEnd
      dockerfile: Dockerfile
    environment: 
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://0.0.0.0:80
    - MYWEBAPI_URL=http://mywebapi
    ports:
    - "5002:80"
    depends_on:
    - mywebapi

  mywebapi:
    image: ${DOCKER_REGISTRY-}mywebapi
    build:
      context: ./MyWebApi
      dockerfile: Dockerfile
    environment: 
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://*:80
    - IdentityUrl=http://identityserver:5000
    ports: 
    - 5001:80
    depends_on:
    - identityserver
  
  identityserver:
    image: ${DOCKER_REGISTRY-}identityserver
    build:
      context: ./IdentityServer
      dockerfile: Dockerfile
    environment: 
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=http://*:5000
    - IDENTITY_ISSUER=http://localhost:5000
    ports:
    - 5000:5000
